功能: 测试用例-验证本地FM播放正常 # features/testcase-2016_08_2413_49_23_170662.feature:2

  场景: 测试用例-验证本地FM播放正常  # features/testcase-2016_08_2413_49_23_170662.feature:3
    当 < 打开收音机应用        # steps/step_launcher.py:14
    当 < 打开FM_AM选择界面    # steps/step_radio.py:10
    当 < 播放指定FM节目       # steps/step_radio.py:15
      | fm_no |
      | 97.5  |
    那么 < 验证播放的FM编号一致   # steps/step_radio.py:21
      | chk_fm_no |
      | 97.5      |

功能: 测试用例-搜索并播放网络电台 # features/testcase-2016_08_2413_49_23_208232.feature:2

  场景: 测试用例-搜索并播放网络电台  # features/testcase-2016_08_2413_49_23_208232.feature:3
    当 < 打开收音机应用       # steps/step_launcher.py:14
    当 < 打开搜索界面        # steps/step_radio.py:108
    当 < 输入电台搜索关键字     # steps/step_radio.py:112
      | key_word |
      | 南京       |
    当 < 随机播放搜索电台      # steps/step_radio.py:137
      | o_result |
      | o_fm     |
      Traceback (most recent call last):
        File "/usr/local/lib/python3.4/configparser.py", line 761, in get
          value = d[option]
        File "/usr/local/lib/python3.4/collections/__init__.py", line 805, in __getitem__
          return self.__missing__(key)            # support subclasses that define __missing__
        File "/usr/local/lib/python3.4/collections/__init__.py", line 797, in __missing__
          raise KeyError(key)
      KeyError: 'socketip'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.4/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.4/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps/step_radio.py", line 141, in step_impl
          fm_no = Radio().click_radio_search_list_title_random_ele()
        File "/home/ogq/pateo/AT/ATP/autotestproject/actions/radio.py", line 602, in click_radio_search_list_title_random_ele
          Utils().raise_Exception_info('收音机搜索结果为空')
        File "/home/ogq/pateo/AT/ATP/autotestproject/utils/utils.py", line 104, in raise_Exception_info
          raise Exception('用例运行失败，' + err_msg + '请参考截图信息: http://' + self.get_conf_value('socketIp') + ':9000/' + time.strftime('%Y%m%d') + '/screenshots/' + png_name)
        File "/home/ogq/pateo/AT/ATP/autotestproject/utils/utils.py", line 175, in get_conf_value
          ret_val = cf.get('baseconf', key)
        File "/usr/local/lib/python3.4/configparser.py", line 764, in get
          raise NoOptionError(option, section)
      configparser.NoOptionError: No option 'socketip' in section: 'baseconf'
      
      Captured stdout:
      /home/ogq/pateo/AT/autotestLog/20160824/screenshots/20160824135035.png
      开始检查应用是否crash

    那么 < 验证播放FM节目一致   # None
      | chk_name |
      | o_result |

